SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS short_codes;
DROP TABLE IF EXISTS services;
-- ALTER TABLE services
-- DROP INDEX short_code_network_type_key;