// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"fmt"
)

type ServicesNetworkType string

const (
	ServicesNetworkTypeMTN     ServicesNetworkType = "MTN"
	ServicesNetworkTypeAIRTEL  ServicesNetworkType = "AIRTEL"
	ServicesNetworkTypeGLO     ServicesNetworkType = "GLO"
	ServicesNetworkType9MOBILE ServicesNetworkType = "9MOBILE"
)

func (e *ServicesNetworkType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServicesNetworkType(s)
	case string:
		*e = ServicesNetworkType(s)
	default:
		return fmt.Errorf("unsupported scan type for ServicesNetworkType: %T", src)
	}
	return nil
}

type ServicesService string

const (
	ServicesServiceSMS          ServicesService = "SMS"
	ServicesServiceUSSD         ServicesService = "USSD"
	ServicesServiceVOICE        ServicesService = "VOICE"
	ServicesServiceSUBSCRIPTION ServicesService = "SUBSCRIPTION"
)

func (e *ServicesService) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServicesService(s)
	case string:
		*e = ServicesService(s)
	default:
		return fmt.Errorf("unsupported scan type for ServicesService: %T", src)
	}
	return nil
}

type ServicesServiceInterface string

const (
	ServicesServiceInterfaceSOAP ServicesServiceInterface = "SOAP"
	ServicesServiceInterfaceHTTP ServicesServiceInterface = "HTTP"
	ServicesServiceInterfaceSMPP ServicesServiceInterface = "SMPP"
)

func (e *ServicesServiceInterface) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServicesServiceInterface(s)
	case string:
		*e = ServicesServiceInterface(s)
	default:
		return fmt.Errorf("unsupported scan type for ServicesServiceInterface: %T", src)
	}
	return nil
}

type ServicesServiceType string

const (
	ServicesServiceTypeDAILY    ServicesServiceType = "DAILY"
	ServicesServiceTypeWEEKLY   ServicesServiceType = "WEEKLY"
	ServicesServiceTypeBIWEEKLY ServicesServiceType = "BI-WEEKLY"
	ServicesServiceTypeMONTHLY  ServicesServiceType = "MONTHLY"
	ServicesServiceTypeONDEMAND ServicesServiceType = "ON-DEMAND"
)

func (e *ServicesServiceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServicesServiceType(s)
	case string:
		*e = ServicesServiceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ServicesServiceType: %T", src)
	}
	return nil
}

type TransactionsDatasyncStatusCode string

const (
	TransactionsDatasyncStatusCodePENDING TransactionsDatasyncStatusCode = "PENDING"
	TransactionsDatasyncStatusCodeSENT    TransactionsDatasyncStatusCode = "SENT"
	TransactionsDatasyncStatusCodeFAILED  TransactionsDatasyncStatusCode = "FAILED"
)

func (e *TransactionsDatasyncStatusCode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsDatasyncStatusCode(s)
	case string:
		*e = TransactionsDatasyncStatusCode(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsDatasyncStatusCode: %T", src)
	}
	return nil
}

type TransactionsGateway string

const (
	TransactionsGatewaySMS  TransactionsGateway = "SMS"
	TransactionsGatewayUSSD TransactionsGateway = "USSD"
	TransactionsGatewayWEB  TransactionsGateway = "WEB"
)

func (e *TransactionsGateway) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsGateway(s)
	case string:
		*e = TransactionsGateway(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsGateway: %T", src)
	}
	return nil
}

type TransactionsNetworkType string

const (
	TransactionsNetworkTypeMTN     TransactionsNetworkType = "MTN"
	TransactionsNetworkTypeAIRTEL  TransactionsNetworkType = "AIRTEL"
	TransactionsNetworkTypeGLO     TransactionsNetworkType = "GLO"
	TransactionsNetworkType9MOBILE TransactionsNetworkType = "9MOBILE"
)

func (e *TransactionsNetworkType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsNetworkType(s)
	case string:
		*e = TransactionsNetworkType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsNetworkType: %T", src)
	}
	return nil
}

type Role struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Service struct {
	ID                      int32                    `json:"id"`
	ShortcodeID             int32                    `json:"shortcode_id"`
	UserID                  int32                    `json:"user_id"`
	ServiceName             string                   `json:"service_name"`
	ServiceID               string                   `json:"service_id"`
	ServiceInterface        ServicesServiceInterface `json:"service_interface"`
	Service                 ServicesService          `json:"service"`
	ServiceType             ServicesServiceType      `json:"service_type"`
	ProductID               string                   `json:"product_id"`
	NodeID                  string                   `json:"node_id"`
	SubscriptionID          string                   `json:"subscription_id"`
	SubscriptionDescription string                   `json:"subscription_description"`
	BaseUrl                 string                   `json:"base_url"`
	DatasyncEndpoint        string                   `json:"datasync_endpoint"`
	NotificationEndpoint    string                   `json:"notification_endpoint"`
	NetworkType             ServicesNetworkType      `json:"network_type"`
	CreatedAt               sql.NullTime             `json:"created_at"`
	UpdatedAt               sql.NullTime             `json:"updated_at"`
}

type ShortCode struct {
	ID        int32        `json:"id"`
	ShortCode string       `json:"short_code"`
	UserID    int32        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Transaction struct {
	ID                      int32                          `json:"id"`
	UserID                  int32                          `json:"user_id"`
	Shortcode               int32                          `json:"shortcode"`
	Msisdn                  string                         `json:"msisdn"`
	Gateway                 TransactionsGateway            `json:"gateway"`
	TransactionID           string                         `json:"transaction_id"`
	SubscriptionID          string                         `json:"subscription_id"`
	SubscriptionDescription string                         `json:"subscription_description"`
	ChargeAmount            string                         `json:"charge_amount"`
	StatusCode              string                         `json:"status_code"`
	ChargingMode            string                         `json:"charging_mode"`
	ValidityType            string                         `json:"validity_type"`
	OperationID             string                         `json:"operation_id"`
	ValidityDays            string                         `json:"validity_days"`
	StatusMessage           string                         `json:"status_message"`
	DatasyncStatusCode      TransactionsDatasyncStatusCode `json:"datasync_status_code"`
	NetworkType             TransactionsNetworkType        `json:"network_type"`
	CreatedAt               sql.NullTime                   `json:"created_at"`
	UpdatedAt               sql.NullTime                   `json:"updated_at"`
}

type User struct {
	ID            int32        `json:"id"`
	Name          string       `json:"name"`
	Password      string       `json:"password"`
	ClientID      string       `json:"client_id"`
	ClientSecret  string       `json:"client_secret"`
	Email         string       `json:"email"`
	PhoneNumber   string       `json:"phone_number"`
	ContactPerson string       `json:"contact_person"`
	RoleID        int32        `json:"role_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}
