// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: user_credential.sql

package db

import (
	"context"
	"database/sql"
)

const createUserCredential = `-- name: CreateUserCredential :execresult
INSERT INTO user_credentials (
  client_id, client_secret, shortcode_id, user_id, service_name, service_id, service, service_type, product_id, node_id, subscription_id, subscription_description, base_url, datasyn_endpoint, notification_endpoint, network_type
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserCredentialParams struct {
	ClientID                string                     `json:"client_id"`
	ClientSecret            string                     `json:"client_secret"`
	ShortcodeID             int32                      `json:"shortcode_id"`
	UserID                  int32                      `json:"user_id"`
	ServiceName             sql.NullString             `json:"service_name"`
	ServiceID               sql.NullString             `json:"service_id"`
	Service                 UserCredentialsService     `json:"service"`
	ServiceType             UserCredentialsServiceType `json:"service_type"`
	ProductID               sql.NullString             `json:"product_id"`
	NodeID                  sql.NullString             `json:"node_id"`
	SubscriptionID          sql.NullString             `json:"subscription_id"`
	SubscriptionDescription sql.NullString             `json:"subscription_description"`
	BaseUrl                 sql.NullString             `json:"base_url"`
	DatasynEndpoint         sql.NullString             `json:"datasyn_endpoint"`
	NotificationEndpoint    sql.NullString             `json:"notification_endpoint"`
	NetworkType             UserCredentialsNetworkType `json:"network_type"`
}

func (q *Queries) CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserCredential,
		arg.ClientID,
		arg.ClientSecret,
		arg.ShortcodeID,
		arg.UserID,
		arg.ServiceName,
		arg.ServiceID,
		arg.Service,
		arg.ServiceType,
		arg.ProductID,
		arg.NodeID,
		arg.SubscriptionID,
		arg.SubscriptionDescription,
		arg.BaseUrl,
		arg.DatasynEndpoint,
		arg.NotificationEndpoint,
		arg.NetworkType,
	)
}

const deleteUserCredential = `-- name: DeleteUserCredential :exec
DELETE FROM user_credentials
WHERE id = ?
`

func (q *Queries) DeleteUserCredential(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserCredential, id)
	return err
}

const getUserCredential = `-- name: GetUserCredential :one
SELECT id, client_id, client_secret, shortcode_id, user_id, service_name, service_id, service, service_type, product_id, node_id, subscription_id, subscription_description, base_url, datasyn_endpoint, notification_endpoint, network_type, created_at, updated_at FROM user_credentials
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserCredential(ctx context.Context, id int32) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, getUserCredential, id)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.ShortcodeID,
		&i.UserID,
		&i.ServiceName,
		&i.ServiceID,
		&i.Service,
		&i.ServiceType,
		&i.ProductID,
		&i.NodeID,
		&i.SubscriptionID,
		&i.SubscriptionDescription,
		&i.BaseUrl,
		&i.DatasynEndpoint,
		&i.NotificationEndpoint,
		&i.NetworkType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserCredential = `-- name: ListUserCredential :many
SELECT id, client_id, client_secret, shortcode_id, user_id, service_name, service_id, service, service_type, product_id, node_id, subscription_id, subscription_description, base_url, datasyn_endpoint, notification_endpoint, network_type, created_at, updated_at FROM user_credentials
ORDER BY id
LIMIT ?
OFFSET ?
`

type ListUserCredentialParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUserCredential(ctx context.Context, arg ListUserCredentialParams) ([]UserCredential, error) {
	rows, err := q.db.QueryContext(ctx, listUserCredential, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCredential
	for rows.Next() {
		var i UserCredential
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecret,
			&i.ShortcodeID,
			&i.UserID,
			&i.ServiceName,
			&i.ServiceID,
			&i.Service,
			&i.ServiceType,
			&i.ProductID,
			&i.NodeID,
			&i.SubscriptionID,
			&i.SubscriptionDescription,
			&i.BaseUrl,
			&i.DatasynEndpoint,
			&i.NotificationEndpoint,
			&i.NetworkType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserCredential = `-- name: UpdateUserCredential :execresult
UPDATE user_credentials SET  service_name= ?, base_url= ?, datasyn_endpoint = ?, notification_endpoint = ?
WHERE id = ?
`

type UpdateUserCredentialParams struct {
	ServiceName          sql.NullString `json:"service_name"`
	BaseUrl              sql.NullString `json:"base_url"`
	DatasynEndpoint      sql.NullString `json:"datasyn_endpoint"`
	NotificationEndpoint sql.NullString `json:"notification_endpoint"`
	ID                   int32          `json:"id"`
}

func (q *Queries) UpdateUserCredential(ctx context.Context, arg UpdateUserCredentialParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserCredential,
		arg.ServiceName,
		arg.BaseUrl,
		arg.DatasynEndpoint,
		arg.NotificationEndpoint,
		arg.ID,
	)
}
