name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:latest
        # command: --default-authentication-plugin=mysql_native_password
        # restart: always
        environment:
          MYSQL_USER: agt
          MYSQL_PASSWORD: Password123
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: agt_middleware_db
      adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
      
    - name: Run Migrations
      run: make migrateup

    - name: Test
      run: make test
